name: CI/CD

on: 
  push:
    branches:
      - master

env:
  CI: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        npm i
    - run: |
        npm run test
    - run: |
        npm run build
    - name: Upload build
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: Build
        # Directory containing files to upload
        path: build

  deploy:
    needs: [build]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v1.0.0
        with:
          # Artifact name
          name: Build
          # Destination path
          path: build
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1.3.0
        with:
          repo: mrsimpson/ical-interceptor
          target_branch: gh-pages
          build_dir: build
          fqdn: ical.no-panic.org
